const fmtInt=new Intl.NumberFormat('pt-BR');
const fmtMoney=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
let dashboard;
const el=id=>document.getElementById(id);
function monthLabel(value){if(!value)return 'Sem data';const [year,month]=value.split('-');return `${month}/${year.slice(2)}`}
function renderBars(metric){const rows=dashboard.pedidos_por_mes;const max=Math.max(1,...rows.map(row=>Number(row[metric]||0)));el('monthlyChart').innerHTML=rows.map(row=>`<div class="bar-item"><span class="bar-value">${metric==='valor'?fmtMoney.format(row.valor):fmtInt.format(row.quantidade)}</span><div class="bar" style="height:${Math.max(2,Number(row[metric]||0)/max*190)}px"></div><span class="bar-label">${monthLabel(row.periodo)}</span></div>`).join('')||'<p>Sem dados para o período.</p>'}
function render(data){dashboard=data;const r=data.resumo;el('orders').textContent=fmtInt.format(r.pedidos);el('orderValue').textContent=fmtMoney.format(r.valor_pedidos);el('invoices').textContent=fmtInt.format(r.notas_fiscais);el('invoiceValue').textContent=fmtMoney.format(r.valor_notas);el('links').textContent=fmtInt.format(r.vinculos_item);el('unlinked').textContent=fmtInt.format(r.notas_sem_vinculo);el('updated').textContent=`Atualizado em ${new Date(data.generated_at).toLocaleString('pt-BR')}`;el('privacy').textContent=data.privacy;el('statusRows').innerHTML=data.pedidos_por_situacao.map(row=>`<tr><td>${String(row.situacao).replaceAll('_',' ')}</td><td>${fmtInt.format(row.quantidade)}</td><td>${fmtMoney.format(row.valor)}</td></tr>`).join('')||'<tr><td colspan="3">Sem dados</td></tr>';renderBars('valor');const orders=new Map(data.pedidos_por_mes.map(row=>[row.periodo,row.valor]));const invoices=new Map(data.notas_por_mes.map(row=>[row.periodo,row.valor]));const months=[...new Set([...orders.keys(),...invoices.keys()])].sort();const max=Math.max(1,...months.flatMap(m=>[orders.get(m)||0,invoices.get(m)||0]));el('comparison').innerHTML='<div class="legend"><span><i class="dot orders"></i>Pedidos</span><span><i class="dot invoices"></i>Notas fiscais</span></div>'+months.map(month=>`<div class="compare-row"><span>${monthLabel(month)}</span><div><div class="track"><i class="orders" style="width:${(orders.get(month)||0)/max*100}%"></i></div><div class="track" style="margin-top:4px"><i class="invoices" style="width:${(invoices.get(month)||0)/max*100}%"></i></div></div><span>${fmtMoney.format(orders.get(month)||0)} / ${fmtMoney.format(invoices.get(month)||0)}</span></div>`).join('')}
el('metric').addEventListener('change',event=>renderBars(event.target.value));
fetch('data/dashboard.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}).then(render).catch(error=>{el('updated').textContent='Dados indisponíveis';el('error').hidden=false;el('error').textContent=`Não foi possível carregar os indicadores: ${error.message}`});
