const $=id=>document.getElementById(id),money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}),integer=new Intl.NumberFormat('pt-BR');let data,filtered=[];
const titles={overview:'Visão geral da carteira',clients:'Clientes e obras',delinquency:'Gestão da inadimplência',installments:'Parcelas da carteira',quality:'Qualidade dos dados'};
function options(id,values){$(id).innerHTML='<option value="">Todos</option>'+[...new Set(values)].sort().map(v=>`<option>${v}</option>`).join('')}
function agingMatch(days,range){if(!range)return true;if(range==='1-30')return days>=1&&days<=30;if(range==='31-60')return days>=31&&days<=60;if(range==='61-90')return days>=61&&days<=90;return days>=91}
function apply(){const query=$('search').value.toLowerCase(),customer=$('customer').value,work=$('work').value,situation=$('situation').value,aging=$('aging-filter').value;filtered=data.parcelas_anonimizadas.filter(r=>(!query||`${r.cliente} ${r.obra}`.toLowerCase().includes(query))&&(!customer||r.cliente===customer)&&(!work||r.obra===work)&&(!situation||r.situacao===situation)&&agingMatch(r.dias_atraso,aging));render()}
function rank(target,rows,label,value){const max=Math.max(1,...rows.map(r=>r[value]));$(target).innerHTML=rows.map(r=>`<div class="rank-row"><span>${r[label]}</span><div class="track"><div class="fill" style="width:${r[value]/max*100}%"></div></div><b>${money.format(r[value])}</b></div>`).join('')||'<p>Sem dados.</p>'}
function group(key){const map=new Map;filtered.forEach(r=>{const k=r[key],v=map.get(k)||{label:k,parcelas:0,saldo:0,vencido:0};v.parcelas++;v.saldo+=r.saldo_atual;if(r.situacao==='INADIMPLENTE')v.vencido+=r.saldo_atual;map.set(k,v)});return [...map.values()]}
function render(){const original=filtered.reduce((s,r)=>s+r.valor_original,0),late=filtered.filter(r=>r.situacao==='INADIMPLENTE').reduce((s,r)=>s+r.saldo_atual,0),future=filtered.filter(r=>r.situacao==='A_VENCER').reduce((s,r)=>s+r.saldo_atual,0),paid=Math.max(0,original-late-future);$('portfolio').textContent=money.format(original);$('installment-count').textContent=`${integer.format(filtered.length)} parcelas`;$('received').textContent=money.format(data.resumo.valor_recebido);$('overdue').textContent=money.format(late);$('future').textContent=money.format(future);$('record-count').textContent=`${filtered.length} parcelas`;$('filter-message').textContent=filtered.length===data.parcelas_anonimizadas.length?'Sem filtros aplicados':'Visão filtrada';const total=Math.max(1,paid+late+future);$('composition').innerHTML=`<div class="segment paid" style="width:${paid/total*100}%">Adimplente</div><div class="segment late" style="width:${late/total*100}%">Vencido</div><div class="segment future" style="width:${future/total*100}%">A vencer</div>`;$('composition-legend').textContent=`Adimplente ${money.format(paid)} · Vencido ${money.format(late)} · A vencer ${money.format(future)}`;const aging=[['1–30 dias',1,30],['31–60 dias',31,60],['61–90 dias',61,90],['Acima de 90',91,999999]].map(([faixa,a,b])=>({faixa,valor:filtered.filter(r=>r.dias_atraso>=a&&r.dias_atraso<=b).reduce((s,r)=>s+r.saldo_atual,0)}));rank('aging',aging,'faixa','valor');const works=group('obra').map(r=>({obra:r.label,valor:r.vencido})).sort((a,b)=>b.valor-a.valor);rank('works',works,'obra','valor');rank('risk-ranking',group('cliente').map(r=>({cliente:r.label,valor:r.vencido})).sort((a,b)=>b.valor-a.valor),'cliente','valor');$('client-rows').innerHTML=group('cliente').map(c=>{const works=[...new Set(filtered.filter(r=>r.cliente===c.label).map(r=>r.obra))].join(', ');return `<tr><td>${c.label}</td><td>${works}</td><td>${c.parcelas}</td><td>${money.format(c.saldo)}</td><td>${money.format(c.vencido)}</td></tr>`}).join('');$('installment-rows').innerHTML=filtered.map(r=>`<tr><td>${r.cliente}</td><td>${r.obra}</td><td>${r.vencimento||'—'}</td><td>${r.situacao.replaceAll('_',' ')}</td><td>${r.dias_atraso}</td><td>${money.format(r.valor_original)}</td><td>${money.format(r.saldo_atual)}</td></tr>`).join('');$('quality-bars').innerHTML=data.completude.map(q=>`<div><strong>${q.campo} · ${q.percentual}%</strong><div class="track"><div class="fill" style="width:${q.percentual}%"></div></div></div>`).join('')}
function exportCsv(){const head='cliente;obra;vencimento;situacao;dias_atraso;valor_original;saldo_atual\n',rows=filtered.map(r=>[r.cliente,r.obra,r.vencimento,r.situacao,r.dias_atraso,r.valor_original,r.saldo_atual].join(';')).join('\n'),url=URL.createObjectURL(new Blob([head+rows],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='carteira-anonimizada.csv';a.click();URL.revokeObjectURL(url)}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');$('page-title').textContent=titles[b.dataset.tab]}));['search','customer','work','situation','aging-filter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',apply));$('clear').addEventListener('click',()=>{['search','customer','work','situation','aging-filter'].forEach(id=>$(id).value='');apply()});$('export').addEventListener('click',exportCsv);
fetch('data/dashboard.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(d=>{data=d;filtered=d.parcelas_anonimizadas||[];options('customer',filtered.map(r=>r.cliente));options('work',filtered.map(r=>r.obra));$('reference').textContent=new Date(`${d.reference_date}T12:00:00`).toLocaleDateString('pt-BR');$('updated').textContent=new Date(d.generated_at).toLocaleString('pt-BR');$('privacy').textContent=d.privacy;render()}).catch(err=>{$('error').hidden=false;$('error').textContent=`Falha ao carregar os dados: ${err.message}`});
